### ISSUE TITLE
Atari port

### ISSUE THREAD

**Issue by polluks** [everslick/push#3]
It works out-of-the-box but Atari's enter key is 155, so you have to type ^M
<img width="784" alt="Bildschirmfoto 2021-04-15 um 14 25 04" src="https://user-images.githubusercontent.com/4707573/114868677-7a0b2b00-9df6-11eb-9597-7b84eabb0ac3.png">

**Comment by everslick** [comment]
WOW, great! The ENTER key can easily be fixed in term.c: term_get_key().

**Comment by everslick** [comment]
care for a PR for the Makefile? I'm not familiar with Atari at all.

**Comment by everslick** [comment]
When you compile with `-DATARI`, the ENTER key should now work.

**Comment by everslick** [comment]
Nevermind, got it working. :)
